scrape_configs:
  
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:9091
        
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: 
      - node_exporter:9100
      
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: 
        - localhost:9090